# Generated by Django 4.2.7 on 2026-01-30 06:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Address",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("receiver", models.CharField(max_length=20, verbose_name="收货人")),
                ("mobile", models.CharField(max_length=11, verbose_name="联系电话")),
                ("region", models.CharField(max_length=100, verbose_name="省市区")),
                ("detail", models.CharField(max_length=255, verbose_name="详细地址")),
                (
                    "is_default",
                    models.BooleanField(default=False, verbose_name="是否默认"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="addresses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "收货地址",
                "db_table": "users_address",
            },
        ),
    ]
