# Generated by Django 4.2.7 on 2026-02-01 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_address"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="bio",
            field=models.TextField(blank=True, null=True, verbose_name="个人简介"),
        ),
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="昵称"
            ),
        ),
    ]
