# Generated by Django 4.2.7 on 2026-02-02 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_bio_user_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verify_status",
            field=models.SmallIntegerField(
                choices=[(0, "未提交"), (1, "审核中"), (2, "已认证"), (3, "认证失败")],
                default=0,
                verbose_name="实名认证状态",
            ),
        ),
    ]
