# Generated by Django 4.2.7 on 2026-02-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_sensitiveword"),
        ("users", "0004_user_verify_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("fake", "虚假信息"),
                            ("advertising", "广告骚扰"),
                            ("insult", "言语辱骂"),
                            ("scam", "诈骗行为"),
                            ("other", "其他原因"),
                        ],
                        max_length=20,
                        verbose_name="举报理由",
                    ),
                ),
                ("content", models.TextField(verbose_name="详情描述")),
                (
                    "status",
                    models.IntegerField(
                        choices=[(0, "待处理"), (1, "已处理")],
                        default=0,
                        verbose_name="处理状态",
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="goods.product",
                        verbose_name="关联商品",
                    ),
                ),
                (
                    "reporter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_made",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="举报人",
                    ),
                ),
                (
                    "target_user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reports_received",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="被举报人",
                    ),
                ),
            ],
            options={
                "verbose_name": "违规举报",
                "verbose_name_plural": "违规举报",
            },
        ),
    ]
