# Generated by Django 4.2.7 on 2026-04-18 12:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_report"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="credit_score",
            field=models.IntegerField(default=70, verbose_name="信用分"),
        ),
        migrations.CreateModel(
            name="CreditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.IntegerField(verbose_name="分值变动")),
                ("reason", models.CharField(max_length=100, verbose_name="变动原因")),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("profile", "完善资料"),
                            ("verify", "实名认证"),
                            ("post_product", "发布商品"),
                            ("trade_done", "完成交易"),
                            ("review_done", "评价商品"),
                            ("penalty", "违规处罚"),
                        ],
                        max_length=20,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="credit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "users_credit_log",
                "ordering": ["-create_time"],
            },
        ),
    ]
