# Generated by Django 4.2.7 on 2026-04-19 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_credit_score_creditlog"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="verify_time",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="实名认证申请时间"
            ),
        ),
    ]
