# Generated by Django 4.2.7 on 2026-01-29 09:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20, verbose_name="分类名称")),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="图标类名"
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="商品标题")),
                ("desc", models.TextField(verbose_name="详细描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "attributes",
                    models.JSONField(blank=True, default=dict, verbose_name="动态属性"),
                ),
                ("images", models.JSONField(default=list, verbose_name="图片列表")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("audit", "审核中"),
                            ("onsale", "在售"),
                            ("sold", "已售出"),
                            ("off", "下架"),
                        ],
                        default="audit",
                        max_length=10,
                    ),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.category",
                        verbose_name="所属分类",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="发布者",
                    ),
                ),
            ],
            options={
                "verbose_name": "二手商品",
                "verbose_name_plural": "二手商品",
            },
        ),
    ]
