# Generated by Django 4.2.7 on 2026-01-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SensitiveWord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "word",
                    models.CharField(max_length=50, unique=True, verbose_name="敏感词"),
                ),
                ("create_time", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "敏感词管理",
                "verbose_name_plural": "敏感词管理",
            },
        ),
    ]
