# Generated by Django 4.2.7 on 2026-04-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_sensitiveword"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="attribute_fields",
            field=models.JSONField(blank=True, default=list, verbose_name="扩展属性"),
        ),
    ]
