# Generated by Django 4.2.7 on 2026-04-14 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0003_category_attribute_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="browse_count",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
        ),
    ]
