# Generated by Django 4.2.7 on 2026-04-14 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0004_category_browse_count"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="browse_count",
        ),
        migrations.AddField(
            model_name="product",
            name="browse_count",
            field=models.PositiveIntegerField(default=0, verbose_name="浏览次数"),
        ),
    ]
