# Generated by Django 4.2.7 on 2026-04-15 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0005_remove_category_browse_count_product_browse_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("audit", "审核中"),
                    ("onsale", "在售"),
                    ("sold", "已售出"),
                    ("off", "下架"),
                    ("banned", "违规下架"),
                ],
                default="audit",
                max_length=10,
            ),
        ),
    ]
