# Generated by Django 4.2.7 on 2026-04-20 09:29

import django.contrib.postgres.indexes
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0007_browsinghistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(
                db_index=True, decimal_places=2, max_digits=10, verbose_name="价格"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="status",
            field=models.CharField(
                choices=[
                    ("audit", "审核中"),
                    ("onsale", "在售"),
                    ("sold", "已售出"),
                    ("off", "下架"),
                    ("banned", "违规下架"),
                ],
                db_index=True,
                default="audit",
                max_length=10,
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["attributes"], name="idx_product_attrs_gin"
            ),
        ),
    ]
