# Generated by Django 4.2.7 on 2026-02-12 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("goods", "0002_sensitiveword"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("trade", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cartitem",
            options={"verbose_name_plural": "购物车"},
        ),
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name_plural": "订单管理"},
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "buyer_score",
                    models.IntegerField(default=5, verbose_name="评分(1-5)"),
                ),
                ("buyer_comment", models.TextField(verbose_name="评价内容")),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review",
                        to="trade.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单评价",
            },
        ),
        migrations.CreateModel(
            name="Favorite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("add_time", models.DateTimeField(auto_now_add=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="goods.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品收藏",
                "unique_together": {("user", "product")},
            },
        ),
    ]
