# Generated by Django 4.2.7 on 2026-03-05 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0002_alter_cartitem_options_alter_order_options_review_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="dispute_reason",
            field=models.TextField(blank=True, null=True, verbose_name="退款/纠纷原因"),
        ),
    ]
