# Generated by Django 4.2.7 on 2026-03-17 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0003_order_dispute_reason"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="dispute_reason",
        ),
        migrations.AddField(
            model_name="order",
            name="refund_reason",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="退款原因"
            ),
        ),
    ]
