# Generated by Django 4.2.7 on 2026-03-17 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0004_remove_order_dispute_reason_order_refund_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("unpaid", "待支付"),
                    ("paid", "已支付"),
                    ("shipped", "已发货"),
                    ("received", "已收货"),
                    ("closed", "已关闭"),
                    ("dispute", "异常/纠纷"),
                    ("arbitrating", "客服介入中"),
                ],
                default="unpaid",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
    ]
