# Generated by Django 4.2.7 on 2026-04-10 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trade", "0005_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="review",
            name="additional_comment",
            field=models.TextField(blank=True, null=True, verbose_name="追加评价"),
        ),
    ]
